### ISSUE TITLE
SPRINT 2 - COMPLIANCE & QUALITY ASSURANCE

### ISSUE THREAD

**Issue by KaueCaponero** [ChallengeFIAP-2023/Buy.it#5]
Faça o desenho da Arquitetura da solução, aplicando TOGAF e usando a ferramenta Archi.
Desenhe em uma mesma página de diagrama no Archi:

- [x] Visão da arquitetura (25 pontos);
- [x] Arquitetura de negócio (25 pontos);
- [x] Arquitetura de sistemas (25 pontos);
- [x] Arquitetura de tecnologia (25 pontos).

Anexar na entrega um arquivo ZIP contendo um PDF com a imagem do seu desenho e um
arquivo TXT contendo nome e RM dos integrantes.

**Comment by mariana-santos** [comment]
Arquitetura finalizada (PDF e arquivo editável na pasta da matéria)
